---
name: openclaw-bot-lifecycle
description: "Execute standardized BOTCTL payloads locally through the installed helper script."
---

# OpenClaw Bot Lifecycle

Use this skill only for standardized `BOTCTL_URL:`, `BOTCTL_FILE:`, or `BOTCTL:` payloads generated by `developer`.

## Local assumptions

1. Current main management agent id is `__MAIN_AGENT_ID__`.
2. Main workspace is `__OPENCLAW_WORKSPACE__`.
3. OpenClaw state root is `__OPENCLAW_STATE_ROOT__`.
4. Use the helper script at:
   - `__OPENCLAW_WORKSPACE__/scripts/openclaw-bot-lifecycle/botctl_local.py`

## Required guards

1. `protocol` must be `botctl/v1`.
2. `skill.name` must be `openclaw-bot-lifecycle`.
3. `invocation.mainOnly`, `security.mainOnly`, and `security.refuseIfNotMain` must all be `true`.
4. `target.openclawMode` must be `standardized`.
5. `target.mainAgentId` and `invocation.targetAgentId` must both equal `__MAIN_AGENT_ID__`.

If any guard fails, return a refusal with the exact reason.

## Execution method

1. For `BOTCTL_URL:` execute:

```bash
python3 __OPENCLAW_WORKSPACE__/scripts/openclaw-bot-lifecycle/botctl_local.py --bundle-url "<exact-url>"
```

2. For `BOTCTL_FILE:` execute:

```bash
python3 __OPENCLAW_WORKSPACE__/scripts/openclaw-bot-lifecycle/botctl_local.py "<exact-payload-file>"
```

3. For inline `BOTCTL:` JSON, write to `/tmp/` and execute the helper with that file.
4. Wait for the helper to exit and return the script output as the final result.

## Expected lifecycle behavior

- `create`: create or update the managed bot shell, and for channel-backed bots also provision the inbound account and route in local OpenClaw state
- `publish`: copy staged files into the managed bot workspace without removing the inbound account or route created during `create`
- `activate`: materialize runtime-ready workspace, agent config, session metadata, and keep the inbound channel wiring in sync
- `delete`: remove only the target bot's managed files, account, route, and dedicated runtime state

## Response format

Success:

```md
Action: <create|publish|delete|activate>
Bot: <botId>
Status: <created|updated|published|deleted|already_absent|activated>
Version: <versionId or ->
Summary: <one sentence>
```

Refusal:

```md
Action: <create|publish|delete|activate|unknown>
Status: refused
Reason: <exact reason>
```
